### ISSUE TITLE
Allow to specify a specific file

### ISSUE THREAD

**Issue by AlexanderWillner** [Samangan/owLint#1]
Steps that will reproduce the problem?
1. ```owlint file.ttl```

What is the expected result?
Check file.ttl

What happens instead?
```file.ttl is not a real directory```

Possible workaround:
Rename file.ttl to folder/file.owl and run ```owlint folder```

Any additional information:
-

**Comment by Samangan** [comment]
You can now pass in a file instead of just a directory.

If there is a .owlint file in the directory where that file lives then it will use that config instead of the default. I have updated the owlint npm app to include this change as well
