### ISSUE TITLE
Set exit code

### ISSUE THREAD

**Issue by AlexanderWillner** [Samangan/owLint#3]
Steps that will reproduce the problem?
1. `owlint folder`

What is the expected result?
A proper exist code.

What happens instead?
Always 0.

Possible workaround:
Parse the output.

Any additional information:

```
$ owlint folder; echo $?
...
Lint Failed!!

------------------------------
Lint Error: 
...
0
```

**Comment by Samangan** [comment]
Hey Alexander,  sorry this is so late. I never got the updates when you made these issues, and this project just sat here collecting dust. Thanks for making these issues, though.

I have fixed this issue and added some integration tests to check for this problem. I also updated the latest version of owlint to version 0.1.0 to include this fix.
